-- Wind Forecast Database Schema
-- Run this script to initialize the database for n8n workflow integration

-- Create forecasts table to store forecast summaries
CREATE TABLE IF NOT EXISTS forecasts (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    location VARCHAR(100) NOT NULL,
    forecast_start TIMESTAMP,
    forecast_end TIMESTAMP,
    avg_wind_speed DECIMAL(5,2),
    max_wind_speed DECIMAL(5,2),
    min_wind_speed DECIMAL(5,2),
    high_wind_hours INTEGER DEFAULT 0,
    gale_hours INTEGER DEFAULT 0,
    max_hourly_change DECIMAL(5,2),
    alert_level VARCHAR(10) CHECK (alert_level IN ('LOW', 'MEDIUM', 'HIGH')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create detailed predictions table
CREATE TABLE IF NOT EXISTS predictions (
    id SERIAL PRIMARY KEY,
    forecast_id INTEGER REFERENCES forecasts(id) ON DELETE CASCADE,
    timestamp TIMESTAMP NOT NULL,
    hour_ahead INTEGER NOT NULL,
    wind_speed_ms DECIMAL(5,2) NOT NULL,
    wind_speed_kmh DECIMAL(5,2) NOT NULL,
    category VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create alerts table for tracking alerts sent
CREATE TABLE IF NOT EXISTS alerts (
    id SERIAL PRIMARY KEY,
    forecast_id INTEGER REFERENCES forecasts(id) ON DELETE CASCADE,
    alert_type VARCHAR(50) NOT NULL,
    alert_level VARCHAR(10) NOT NULL,
    message TEXT,
    sent_to VARCHAR(100),
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_forecasts_timestamp ON forecasts(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_forecasts_location ON forecasts(location);
CREATE INDEX IF NOT EXISTS idx_forecasts_alert_level ON forecasts(alert_level);
CREATE INDEX IF NOT EXISTS idx_predictions_forecast_id ON predictions(forecast_id);
CREATE INDEX IF NOT EXISTS idx_predictions_timestamp ON predictions(timestamp);
CREATE INDEX IF NOT EXISTS idx_alerts_forecast_id ON alerts(forecast_id);
CREATE INDEX IF NOT EXISTS idx_alerts_sent_at ON alerts(sent_at DESC);

-- Create view for latest forecasts
CREATE OR REPLACE VIEW latest_forecasts AS
SELECT 
    f.*,
    COUNT(p.id) as prediction_count,
    COUNT(a.id) as alert_count
FROM forecasts f
LEFT JOIN predictions p ON f.id = p.forecast_id
LEFT JOIN alerts a ON f.id = a.forecast_id
GROUP BY f.id
ORDER BY f.timestamp DESC
LIMIT 10;

-- Create view for high-risk periods
CREATE OR REPLACE VIEW high_risk_forecasts AS
SELECT *
FROM forecasts
WHERE alert_level IN ('HIGH', 'MEDIUM')
ORDER BY timestamp DESC;

-- Insert sample data (optional - for testing)
-- DELETE FROM forecasts; -- Uncomment to clear existing data

COMMENT ON TABLE forecasts IS 'Summary of wind forecasts generated by the system';
COMMENT ON TABLE predictions IS 'Detailed hourly predictions for each forecast';
COMMENT ON TABLE alerts IS 'Log of alerts sent for each forecast';

-- Grant permissions (adjust user as needed)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO windforecast;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO windforecast;

-- Display table info
SELECT 'Database initialized successfully!' AS status;
SELECT table_name, 
       (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = t.table_name) as column_count
FROM information_schema.tables t
WHERE table_schema = 'public' 
  AND table_type = 'BASE TABLE'
ORDER BY table_name;
